# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confrence', '0011_auto_20160426_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='topics',
        ),
    ]
