# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confrence', '0013_auto_20160426_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='confrence.Author'),
        ),
    ]
