# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confrence', '0014_auto_20160426_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperSubmission',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='confrence.Submission')),
                ('filesize', models.CharField(max_length=30)),
            ],
            bases=('confrence.submission',),
        ),
    ]
