# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confrence', '0016_postersubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersubmission',
            name='filesize',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='postersubmission',
            name='filesize',
            field=models.IntegerField(max_length=30),
        ),
    ]
