# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confrence', '0021_submission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='confrence.Reviewr'),
        ),
    ]
