# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confrence', '0022_submission_reviewr'),
    ]

    operations = [
        migrations.AddField(
            model_name='confrence',
            name='pcChair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
