# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confrence', '0023_confrence_pcchair'),
    ]

    operations = [
        migrations.AddField(
            model_name='confrence',
            name='notifyDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='acceptance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='final_comment',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
