# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 16:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confrence', '0023_confrence_pcchair'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='confrence',
            name='accountNo',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='confrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confrence.Confrence'),
        ),
    ]
