# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confrence', '0024_auto_20160427_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confrence',
            name='pcChair',
            field=models.ForeignKey(default=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
