# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confrence', '0026_auto_20160427_1618'),
        ('confrence', '0025_auto_20160427_1709'),
    ]

    operations = [
    ]
